.TH DOCUMENTACION DEL CLIENTE

.SH NAME
cliente

.SH SYNOPSIS
cliente

.SH DESCRIPTION
Programa del cliente del juego de pokémon. El cliente solicita iniciar el juego 
proporcionando un ID de usuario. 

Una vez que se inició sesión el usuario puede consultar los pokémon que ya ha atrapado,
atrapar un nuevo pokémon o una aventura.

.SH AUTHORS
Adrián Vélez
.br
América García
.br
Lisandro Vázquez
