.TH DOCUMENTACION DEL SERVIDOR

.SH NAME
servidor

.SH SYNOPSIS
servidor

.SH DESCRIPTION
Programa del servidor del juego de Pokemon. Recibe conexiones de los clientes
utilizando un nuevo protocolo de la capa de aplicación.

Una vez que se inició sesión, el cliente puede solicitar ver qué pokémones ha
atrapado hasta el momento o capturar un nuevo pokémon. Dependiendo de esto,
el servidor sabe exactamente qué debe enviar.

.SH AUTHORS
Adrián Vélez
.br
América García
.br
Lisandro Vázquez
