ENVIO_IP = 1
ID_ENCONTRADO = 2
LISTA_POKEMON = 3
POKEMON_REPETIDO = 4
SALIR = 5
CONSULTA_POKEMON = 6
RECIBIDO = 7
SOLICITA_CAPTURA = 10
CAPTURAR_POKEMON = 20
INTENTAR_CAPTURA = 21
ENVIO_POKEMON = 22
SI = 30
NO = 31
TERMINANDO_SESION = 32
ID_NO_ENCONTRADO = 40
NO_MAS_INTENTOS = 41
NO_MAS_CAPTURAS = 42

